local CoastingLibrary = loadstring(game:HttpGet("https://pastebin.com/raw/3gQQtaKX"))()

local AimbotTab = CoastingLibrary:CreateTab("Auto Infinity")
local MainSection = AimbotTab:CreateSection("Main")
local ConfigSection = AimbotTab:CreateSection("configs")

MainSection:CreateToggle("Inf Stamina", function(boolean)
   print("Infinity Stamina:", boolean)
end)
MainSection:CreateToggle("Inf StrikingPower", function(boolean)
   print("Infinity StrikingPower:", boolean)
end)
MainSection:CreateToggle("Inf Custom Statas", function(boolean)
   print("Infinity StrikingPower:", boolean)
end)
MainSection:CreateToggle("Inf Stamina", function(boolean)
   print("Infinity StrikingPower:", boolean)
end)
MainSection:CreateToggle("Inf Fatigue", function(boolean)
   print("Infinity StrikingPower:", boolean)
end)
ConfigSection:CreateToggle("Fly", function(boolean)
   print("Infinity StrikingPower:", boolean)
end)
ConfigSection:CreateSlider("Setting Fly", 0, 150, 50, false, function(value)
   print("Field of View: " .. value)
end)


ConfigSection:CreateToggle("Walk Speed", function(boolean)
   print("Infinity StrikingPower:", boolean)
end)
ConfigSection:CreateSlider("Setting Walk Speed", 0, 150, 50, false, function(value)
   print("Field of View: " .. value)
end)
ConfigSection:CreateToggle("No Chip", function(boolean)
   print("Infinity StrikingPower:", boolean)
end)
ConfigSection:CreateButton("Discord : ItsBlack#1606", function()
   print("Boo!")    
end)
MainSection:CreateButton("Discord : ItsBlack#1606", function()
   print("Boo!")    
end)
local KimbotTab = CoastingLibrary:CreateTab("Auto Quest")


ConfigSection:CreateSlider("Setting Fly", 0, 150, 50, false, function(value)
   print("Field of View: " .. value)
end)


ConfigSection:CreateToggle("Walk Speed", function(boolean)
   print("Infinity StrikingPower:", boolean)
end)
ConfigSection:CreateSlider("Setting Walk Speed", 0, 150, 50, false, function(value)
   print("Field of View: " .. value)
end)
ConfigSection:CreateToggle("No Chip", function(boolean)
   print("Infinity StrikingPower:", boolean)
end)
ConfigSection:CreateButton("Discord : ItsBlack#1606", function()
   print("Boo!")    
end)
MainSection:CreateButton("Discord : ItsBlack#1606", function()
   print("Boo!")    
end)
local KimbotTab = CoastingLibrary:CreateTab("Auto Quest")

